/*
 * Copyright (C) 2019 Álvaro Morcillo Barbero
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import rojeru_san.RSPanelsSlider;
import util.OperacionesBDD;

/**
 *
 * @author Álvaro Morcillo Barbero
 */
public class Frame_Bienvenida extends JFrame {

    private CardLayout cardLayout;
    private final static Logger logger = Logger.getLogger(Frame_Bienvenida.class.getName());
    private OperacionesBDD operacionesBDD;
    private boolean conexionEstablecida = false;

    /**
     * Creates new form Dialog_IntroducirEmpresa
     */
    public Frame_Bienvenida() {

        initComponents();

        cardLayout = (CardLayout) panelSlider.getLayout();
        setLocationRelativeTo(null);
        lblConsola.setVisible(false);
        operacionesBDD = new OperacionesBDD();
        
        cancelarURL.setVisible(false);
        cancelarUsuario.setVisible(false);
        cancelarContraseña.setVisible(false);
        /*
        try {
            
            operacionesBDD.iniciarConexion();
            operacionesBDD.introducirEmpresa("Empresa TEST", "S.L", "001232323SL",
                    "alvaro.morcillo@hotmail.com", "alvaro.morcillo@hotmail.com",
                    "Cuenca 5", "Tobarra", "Albacete", "02500", "España");     
            operacionesBDD.cerrarConexion();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Frame_Bienvenida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Frame_Bienvenida.class.getName()).log(Level.SEVERE, null, ex);
        }
         */
    }

    /**
     * Este método recibe un label, el cual cambiará el color y el texto según
     * los parámetros introducidos. ATENCION Lo hace visible
     *
     * @param label
     * @param bool
     * @param mensaje
     */
    private void mensajeConsola(JLabel label, String mensaje, boolean bool) {
        label.setText(mensaje);
        if (bool) {
            label.setForeground(Color.GREEN.darker());
        } else {
            label.setForeground(Color.RED);
        }

        if (!label.isVisible()) {
            label.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        foregroundPanel = new javax.swing.JPanel();
        panelSlider = new rojeru_san.RSPanelsSlider();
        panelBienvenida = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        rSPanelImage2 = new rojerusan.RSPanelImage();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        botonSiguiente = new rojerusan.RSButtonMetro();
        panelBaseDatos = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cancelarURL = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        lblURL = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        cancelarUsuario = new javax.swing.JLabel();
        cancelarContraseña = new javax.swing.JLabel();
        lblPassword = new javax.swing.JPasswordField();
        jLabel48 = new javax.swing.JLabel();
        botonComprobarConexion = new java.awt.Button();
        lblConsola = new javax.swing.JLabel();
        lblUser = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        panelSuperior1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        rSPanelImage3 = new rojerusan.RSPanelImage();
        botonSiguiente2 = new rojerusan.RSButtonMetro();
        jLabel22 = new javax.swing.JLabel();
        panelBaseDatos1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jTextField17 = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel41 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel39 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        botonSiguiente3 = new rojerusan.RSButtonMetro();
        panelSuperior2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        rSPanelImage4 = new rojerusan.RSPanelImage();
        rSButton1 = new rojeru_san.RSButton();
        panelEmpresa1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        botonSiguiente4 = new rojerusan.RSButtonMetro();
        panelSuperior3 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        rSPanelImage5 = new rojerusan.RSPanelImage();
        panelEmpresa2 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jTextField12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        botonSiguiente5 = new rojerusan.RSButtonMetro();
        panelSuperior4 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        rSPanelImage6 = new rojerusan.RSPanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        backgroundPanel.setBackground(new java.awt.Color(0, 0, 0));

        foregroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        panelBienvenida.setBackground(new java.awt.Color(255, 255, 255));
        panelBienvenida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSuperior.setBackground(new java.awt.Color(79, 134, 198));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("¡Bienvenido!");

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/ui/images/logo/logo_transparent.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage2Layout = new javax.swing.GroupLayout(rSPanelImage2);
        rSPanelImage2.setLayout(rSPanelImage2Layout);
        rSPanelImage2Layout.setHorizontalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        rSPanelImage2Layout.setVerticalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addComponent(rSPanelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(211, 211, 211))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(rSPanelImage2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelBienvenida.add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 80));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 22)); // NOI18N
        jLabel11.setText("<html>No te preocupes, solo tendrás<br/>que configurar algunos <br/>parámetros y podrás empezar<br>a utilizar la aplicación</br></html>");
        panelBienvenida.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 340, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/logo/logo_transparent_1.png"))); // NOI18N
        panelBienvenida.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 270, 230));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel15.setText("1/5");
        panelBienvenida.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 40, 40));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel20.setText("<html>¡Vaya! , parece que es la<br/>primera vez que utilizas <br/><b>OrderTracker</b>.</html>");
        panelBienvenida.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 350, -1));

        botonSiguiente.setBackground(new java.awt.Color(79, 134, 198));
        botonSiguiente.setText("Siguiente");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });
        panelBienvenida.add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 120, 40));

        panelSlider.add(panelBienvenida, "card4");

        panelBaseDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelBaseDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel25.setText("Necesitamos una base de datos para que puedas utilizar");
        panelBaseDatos.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 520, -1));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel26.setText("OrderTracker");
        panelBaseDatos.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel23.setText("Usuario:");
        panelBaseDatos.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel27.setText("Contraseña:");
        panelBaseDatos.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel29.setText("URL:");
        panelBaseDatos.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        cancelarURL.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        cancelarURL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelBaseDatos.add(cancelarURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jSeparator15.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator15.setForeground(new java.awt.Color(55, 147, 114));
        panelBaseDatos.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 380, 10));

        lblURL.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        lblURL.setBorder(null);
        panelBaseDatos.add(lblURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 368, 25));

        jSeparator16.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator16.setForeground(new java.awt.Color(55, 147, 114));
        panelBaseDatos.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 368, 10));

        cancelarUsuario.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        cancelarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelBaseDatos.add(cancelarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        cancelarContraseña.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        cancelarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelBaseDatos.add(cancelarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        lblPassword.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lblPassword.setBorder(null);
        lblPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblPasswordActionPerformed(evt);
            }
        });
        panelBaseDatos.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 370, 28));

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel48.setText("Comprobar conexión");
        panelBaseDatos.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        botonComprobarConexion.setBackground(new java.awt.Color(0, 204, 102));
        botonComprobarConexion.setForeground(new java.awt.Color(51, 51, 0));
        botonComprobarConexion.setLabel("OK");
        botonComprobarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprobarConexionActionPerformed(evt);
            }
        });
        panelBaseDatos.add(botonComprobarConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        lblConsola.setBackground(new java.awt.Color(255, 255, 255));
        lblConsola.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblConsola.setForeground(new java.awt.Color(0, 204, 0));
        lblConsola.setText("Conexión establecida correctamente");
        panelBaseDatos.add(lblConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 425, -1));

        lblUser.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        lblUser.setBorder(null);
        panelBaseDatos.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 368, 25));

        jSeparator17.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator17.setForeground(new java.awt.Color(55, 147, 114));
        panelBaseDatos.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 368, 10));

        panelSuperior1.setBackground(new java.awt.Color(79, 134, 198));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Creación de la base de datos");

        rSPanelImage3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/ui/images/logo/logo_transparent.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage3Layout = new javax.swing.GroupLayout(rSPanelImage3);
        rSPanelImage3.setLayout(rSPanelImage3Layout);
        rSPanelImage3Layout.setHorizontalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        rSPanelImage3Layout.setVerticalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSuperior1Layout = new javax.swing.GroupLayout(panelSuperior1);
        panelSuperior1.setLayout(panelSuperior1Layout);
        panelSuperior1Layout.setHorizontalGroup(
            panelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperior1Layout.createSequentialGroup()
                .addComponent(rSPanelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(211, 211, 211))
        );
        panelSuperior1Layout.setVerticalGroup(
            panelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperior1Layout.createSequentialGroup()
                .addGroup(panelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(rSPanelImage3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelBaseDatos.add(panelSuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 80));

        botonSiguiente2.setBackground(new java.awt.Color(79, 134, 198));
        botonSiguiente2.setText("Siguiente");
        botonSiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguiente2ActionPerformed(evt);
            }
        });
        panelBaseDatos.add(botonSiguiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 120, 40));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel22.setText("2/5");
        panelBaseDatos.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 40, 40));

        panelSlider.add(panelBaseDatos, "card4");

        panelBaseDatos1.setBackground(new java.awt.Color(255, 255, 255));
        panelBaseDatos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel28.setText("3/5");
        panelBaseDatos1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 40, 40));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel30.setText("Ahora tendrás que crear un usuario administrador. Con este usuario,");
        panelBaseDatos1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 610, 20));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel34.setText("podrás, consultar y modificar datos, así como crear otros ");
        panelBaseDatos1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 570, 20));

        jLabel35.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel35.setText("Contraseña:");
        panelBaseDatos1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 20));

        jLabel36.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel36.setText("Confirma contraseña:");
        panelBaseDatos1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 220, 20));

        jLabel37.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel37.setText("Nombre de usuario:");
        panelBaseDatos1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 200, 20));

        jLabel38.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelBaseDatos1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, 30));

        jSeparator18.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator18.setForeground(new java.awt.Color(55, 147, 114));
        panelBaseDatos1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 320, 10));

        jTextField17.setFont(new java.awt.Font("Courier New", 0, 15)); // NOI18N
        jTextField17.setBorder(null);
        panelBaseDatos1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 320, 30));

        jSeparator19.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator19.setForeground(new java.awt.Color(55, 147, 114));
        panelBaseDatos1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 320, 20));

        jLabel40.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelBaseDatos1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jPasswordField2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPasswordField2.setBorder(null);
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        panelBaseDatos1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 320, 30));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel41.setText("usuarios de más bajo nivel que el tuyo, como empleados.");
        panelBaseDatos1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 550, 20));

        jSeparator20.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator20.setForeground(new java.awt.Color(55, 147, 114));
        panelBaseDatos1.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 320, 20));

        jLabel42.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelBaseDatos1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 30, 30));

        jPasswordField3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPasswordField3.setBorder(null);
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        panelBaseDatos1.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 320, 30));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel39.setText("Pincha aquí");
        panelBaseDatos1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 120, -1));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel43.setText("Si ya tienes un usuario en esta base de datos");
        panelBaseDatos1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 430, 20));

        botonSiguiente3.setBackground(new java.awt.Color(79, 134, 198));
        botonSiguiente3.setText("Siguiente");
        botonSiguiente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguiente3ActionPerformed(evt);
            }
        });
        panelBaseDatos1.add(botonSiguiente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 120, 40));

        panelSuperior2.setBackground(new java.awt.Color(79, 134, 198));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Crear administrador");

        rSPanelImage4.setImagen(new javax.swing.ImageIcon(getClass().getResource("/ui/images/logo/logo_transparent.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage4Layout = new javax.swing.GroupLayout(rSPanelImage4);
        rSPanelImage4.setLayout(rSPanelImage4Layout);
        rSPanelImage4Layout.setHorizontalGroup(
            rSPanelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        rSPanelImage4Layout.setVerticalGroup(
            rSPanelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSuperior2Layout = new javax.swing.GroupLayout(panelSuperior2);
        panelSuperior2.setLayout(panelSuperior2Layout);
        panelSuperior2Layout.setHorizontalGroup(
            panelSuperior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperior2Layout.createSequentialGroup()
                .addComponent(rSPanelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        panelSuperior2Layout.setVerticalGroup(
            panelSuperior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperior2Layout.createSequentialGroup()
                .addGroup(panelSuperior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(rSPanelImage4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelBaseDatos1.add(panelSuperior2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 80));

        rSButton1.setText("...");
        panelBaseDatos1.add(rSButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 60, 40));

        panelSlider.add(panelBaseDatos1, "card4");

        panelEmpresa1.setBackground(new java.awt.Color(255, 255, 255));
        panelEmpresa1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setBorder(null);
        panelEmpresa1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 218, 234, -1));

        jSeparator1.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator1.setForeground(new java.awt.Color(55, 147, 114));
        panelEmpresa1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 236, 234, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nombre");
        panelEmpresa1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 195, -1, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setBorder(null);
        panelEmpresa1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 282, 234, -1));

        jSeparator2.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator2.setForeground(new java.awt.Color(55, 147, 114));
        panelEmpresa1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 300, 234, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("CIF");
        panelEmpresa1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 258, -1, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setBorder(null);
        panelEmpresa1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 346, 234, -1));

        jSeparator3.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator3.setForeground(new java.awt.Color(55, 147, 114));
        panelEmpresa1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 364, 234, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        panelEmpresa1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 322, -1, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.setBorder(null);
        panelEmpresa1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 213, 234, -1));

        jSeparator4.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator4.setForeground(new java.awt.Color(55, 147, 114));
        panelEmpresa1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 231, 234, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Forma Jurídica");
        panelEmpresa1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 189, -1, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setBorder(null);
        panelEmpresa1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 282, 234, -1));

        jSeparator5.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator5.setForeground(new java.awt.Color(55, 147, 114));
        panelEmpresa1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 300, 234, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Teléfono");
        panelEmpresa1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 264, -1, -1));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField6.setBorder(null);
        panelEmpresa1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 346, 234, -1));

        jSeparator6.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator6.setForeground(new java.awt.Color(55, 147, 114));
        panelEmpresa1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 364, 234, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("<html> <b> Paypal </b> (opcional) <html>");
        panelEmpresa1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 322, 234, -1));

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel45.setText("4/5");
        panelEmpresa1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 40, 40));

        jLabel50.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelEmpresa1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 215, -1, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelEmpresa1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 215, -1, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelEmpresa1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 284, -1, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelEmpresa1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 284, -1, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelEmpresa1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 348, -1, -1));

        botonSiguiente4.setBackground(new java.awt.Color(79, 134, 198));
        botonSiguiente4.setText("Siguiente");
        botonSiguiente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguiente4ActionPerformed(evt);
            }
        });
        panelEmpresa1.add(botonSiguiente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 120, 40));

        panelSuperior3.setBackground(new java.awt.Color(79, 134, 198));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Datos de tu empresa");

        rSPanelImage5.setImagen(new javax.swing.ImageIcon(getClass().getResource("/ui/images/logo/logo_transparent.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage5Layout = new javax.swing.GroupLayout(rSPanelImage5);
        rSPanelImage5.setLayout(rSPanelImage5Layout);
        rSPanelImage5Layout.setHorizontalGroup(
            rSPanelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        rSPanelImage5Layout.setVerticalGroup(
            rSPanelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSuperior3Layout = new javax.swing.GroupLayout(panelSuperior3);
        panelSuperior3.setLayout(panelSuperior3Layout);
        panelSuperior3Layout.setHorizontalGroup(
            panelSuperior3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperior3Layout.createSequentialGroup()
                .addComponent(rSPanelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        panelSuperior3Layout.setVerticalGroup(
            panelSuperior3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperior3Layout.createSequentialGroup()
                .addGroup(panelSuperior3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(rSPanelImage5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelEmpresa1.add(panelSuperior3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 80));

        panelSlider.add(panelEmpresa1, "card2");

        panelEmpresa2.setBackground(new java.awt.Color(255, 255, 255));
        panelEmpresa2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField8.setBorder(null);
        panelEmpresa2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 157, 234, -1));

        jSeparator8.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator8.setForeground(new java.awt.Color(55, 147, 114));
        panelEmpresa2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 180, 234, 10));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField9.setBorder(null);
        panelEmpresa2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 157, 234, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Calle");
        panelEmpresa2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 133, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator9.setForeground(new java.awt.Color(55, 147, 114));
        panelEmpresa2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 180, 234, 10));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField10.setBorder(null);
        panelEmpresa2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 220, 234, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Localidad");
        panelEmpresa2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 133, -1, -1));

        jSeparator10.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator10.setForeground(new java.awt.Color(55, 147, 114));
        panelEmpresa2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 243, 234, 10));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Provincia");
        panelEmpresa2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 196, -1, -1));

        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField11.setBorder(null);
        panelEmpresa2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 289, 234, -1));

        jSeparator11.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator11.setForeground(new java.awt.Color(55, 147, 114));
        panelEmpresa2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 312, 234, 10));

        jTextField12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField12.setBorder(null);
        panelEmpresa2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 226, 234, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("País");
        panelEmpresa2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 265, -1, -1));

        jSeparator12.setBackground(new java.awt.Color(55, 147, 114));
        jSeparator12.setForeground(new java.awt.Color(55, 147, 114));
        panelEmpresa2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 249, 234, 10));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Codigo Postal");
        panelEmpresa2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 202, -1, -1));

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel47.setText("5/5");
        panelEmpresa2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, 40));

        jLabel55.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelEmpresa2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 164, -1, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelEmpresa2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 227, -1, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelEmpresa2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 296, -1, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelEmpresa2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 164, -1, -1));

        jLabel59.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icons8_cancel_26px_1.png"))); // NOI18N
        panelEmpresa2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 233, -1, -1));

        botonSiguiente5.setBackground(new java.awt.Color(79, 134, 198));
        botonSiguiente5.setText("Siguiente");
        botonSiguiente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguiente5ActionPerformed(evt);
            }
        });
        panelEmpresa2.add(botonSiguiente5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 120, 40));

        panelSuperior4.setBackground(new java.awt.Color(79, 134, 198));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Datos de tu empresa");

        rSPanelImage6.setImagen(new javax.swing.ImageIcon(getClass().getResource("/ui/images/logo/logo_transparent.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage6Layout = new javax.swing.GroupLayout(rSPanelImage6);
        rSPanelImage6.setLayout(rSPanelImage6Layout);
        rSPanelImage6Layout.setHorizontalGroup(
            rSPanelImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        rSPanelImage6Layout.setVerticalGroup(
            rSPanelImage6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSuperior4Layout = new javax.swing.GroupLayout(panelSuperior4);
        panelSuperior4.setLayout(panelSuperior4Layout);
        panelSuperior4Layout.setHorizontalGroup(
            panelSuperior4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperior4Layout.createSequentialGroup()
                .addComponent(rSPanelImage6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        panelSuperior4Layout.setVerticalGroup(
            panelSuperior4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperior4Layout.createSequentialGroup()
                .addGroup(panelSuperior4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(rSPanelImage6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelEmpresa2.add(panelSuperior4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 80));

        panelSlider.add(panelEmpresa2, "card3");

        javax.swing.GroupLayout foregroundPanelLayout = new javax.swing.GroupLayout(foregroundPanel);
        foregroundPanel.setLayout(foregroundPanelLayout);
        foregroundPanelLayout.setHorizontalGroup(
            foregroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        foregroundPanelLayout.setVerticalGroup(
            foregroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(foregroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(foregroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonComprobarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprobarConexionActionPerformed

        //*****************************
        //Comprueba que los campos de texto no estén vacios
        //Activa/Desactiva los iconos de cancelar
        if (lblURL.getText().equals("")) {
            cancelarURL.setVisible(true);
        } else {
            cancelarURL.setVisible(false);
        }
        if (lblUser.getText().equals("")) {
            cancelarUsuario.setVisible(true);
        } else {
            cancelarUsuario.setVisible(false);
        }
        if (String.valueOf(lblPassword.getPassword()).equals("")) {
            cancelarContraseña.setVisible(true);
        } else {
            cancelarContraseña.setVisible(false);
        }

        //****************************

        //***************************
        //Comprueba la conexion
        conexionEstablecida = OperacionesBDD.comprobarConexion(this.lblURL.getText(),
            this.lblUser.getText(),
            String.valueOf(this.lblPassword.getPassword()));

        //Muestra el mensaje en la consola
        if (conexionEstablecida) {
            mensajeConsola(lblConsola, "Conexion establecida correctamente", true);
            //botonSiguiente1.setEnabled(true);
        } else {
            mensajeConsola(lblConsola, "No se ha podido establecer la conexion", false);
            //botonSiguiente1.setEnabled(false);
        }
        //***************************
    }//GEN-LAST:event_botonComprobarConexionActionPerformed

    private void lblPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblPasswordActionPerformed
        
    }//GEN-LAST:event_lblPasswordActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        panelSlider.siguiente(RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void botonSiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguiente2ActionPerformed
        panelSlider.siguiente(RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_botonSiguiente2ActionPerformed

    private void botonSiguiente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguiente3ActionPerformed
        panelSlider.siguiente(RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_botonSiguiente3ActionPerformed

    private void botonSiguiente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguiente4ActionPerformed
        panelSlider.siguiente(RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_botonSiguiente4ActionPerformed

    private void botonSiguiente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguiente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSiguiente5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frame_Bienvenida dialog = new Frame_Bienvenida();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private java.awt.Button botonComprobarConexion;
    private rojerusan.RSButtonMetro botonSiguiente;
    private rojerusan.RSButtonMetro botonSiguiente2;
    private rojerusan.RSButtonMetro botonSiguiente3;
    private rojerusan.RSButtonMetro botonSiguiente4;
    private rojerusan.RSButtonMetro botonSiguiente5;
    private javax.swing.JLabel cancelarContraseña;
    private javax.swing.JLabel cancelarURL;
    private javax.swing.JLabel cancelarUsuario;
    private javax.swing.JPanel foregroundPanel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblConsola;
    private javax.swing.JPasswordField lblPassword;
    private javax.swing.JTextField lblURL;
    private javax.swing.JTextField lblUser;
    private javax.swing.JPanel panelBaseDatos;
    private javax.swing.JPanel panelBaseDatos1;
    private javax.swing.JPanel panelBienvenida;
    private javax.swing.JPanel panelEmpresa1;
    private javax.swing.JPanel panelEmpresa2;
    private rojeru_san.RSPanelsSlider panelSlider;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelSuperior1;
    private javax.swing.JPanel panelSuperior2;
    private javax.swing.JPanel panelSuperior3;
    private javax.swing.JPanel panelSuperior4;
    private rojeru_san.RSButton rSButton1;
    private rojerusan.RSPanelImage rSPanelImage2;
    private rojerusan.RSPanelImage rSPanelImage3;
    private rojerusan.RSPanelImage rSPanelImage4;
    private rojerusan.RSPanelImage rSPanelImage5;
    private rojerusan.RSPanelImage rSPanelImage6;
    // End of variables declaration//GEN-END:variables
}
