/*
 * Copyright (C) 2019 Álvaro Morcillo Barbero
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ui.dialogs;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.text.JTextComponent;
import pojos.Usuario;
import static ui.dialogs.Dialog_cambiarContraseña.RET_OK;
import util.OperacionesBDD;
import util.Util;

/**
 *
 * @author alvaro2226
 */
public class Dialog_nuevoUsuario extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    Usuario usuario = new Usuario();
    ArrayList<JTextComponent> componentes = new ArrayList<>();

    public Dialog_nuevoUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();

        pack();
        this.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width)/2 - getWidth()/2, (Toolkit.getDefaultToolkit().getScreenSize().height)/2 - getHeight()/2);
        //Para comprobar si estan vacios mas tarde
        componentes.add(this.fieldApellidos);
        componentes.add(this.fieldDNI);
        componentes.add(this.fieldEmail);
        componentes.add(this.fieldNom);
        componentes.add(this.fieldNomUsuario1);
        componentes.add(this.fieldTelefono);
        componentes.add(this.lblContraActual);

        lblConsola.setVisible(false);

        comboRol.addItem(
                "Empleado");

    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        botonConfirmar = new rojerusan.RSButtonHover();
        botonCancelar = new rojerusan.RSButtonHover();
        labelNombreProducto11 = new javax.swing.JLabel();
        lblContraActual = new rojeru_san.RSMPassView();
        labelNombreProducto10 = new javax.swing.JLabel();
        fieldNom = new rojerusan.RSMetroTextFullPlaceHolder();
        labelNombreProducto5 = new javax.swing.JLabel();
        fieldEmail = new rojerusan.RSMetroTextFullPlaceHolder();
        labelNombreProducto6 = new javax.swing.JLabel();
        fieldTelefono = new rojerusan.RSMetroTextFullPlaceHolder();
        labelNombreProducto7 = new javax.swing.JLabel();
        fieldDNI = new rojerusan.RSMetroTextFullPlaceHolder();
        labelNombreProducto4 = new javax.swing.JLabel();
        labelNombreProducto9 = new javax.swing.JLabel();
        comboRol = new rojerusan.RSComboMetro();
        fieldNomUsuario1 = new rojerusan.RSMetroTextFullPlaceHolder();
        labelNombreProducto8 = new javax.swing.JLabel();
        fieldApellidos = new rojerusan.RSMetroTextFullPlaceHolder();
        lblConsola = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonConfirmar.setBackground(new java.awt.Color(55, 147, 114));
        botonConfirmar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonConfirmar.setText("Confirmar ");
        botonConfirmar.setColorHover(new java.awt.Color(70, 198, 136));
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });
        panelFondo.add(botonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 120, -1));

        botonCancelar.setBackground(new java.awt.Color(235, 86, 64));
        botonCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCancelar.setText("Cancelar");
        botonCancelar.setColorHover(new java.awt.Color(255, 153, 153));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelFondo.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 120, -1));

        labelNombreProducto11.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreProducto11.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        labelNombreProducto11.setText("Contraseña ");
        panelFondo.add(labelNombreProducto11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 402, 140, 40));

        lblContraActual.setPlaceholder("");
        lblContraActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblContraActualActionPerformed(evt);
            }
        });
        panelFondo.add(lblContraActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        labelNombreProducto10.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreProducto10.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        labelNombreProducto10.setText("Nombre de usuario");
        panelFondo.add(labelNombreProducto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 82, 220, 40));

        fieldNom.setText("Álvaro");
        fieldNom.setPlaceholder("");
        panelFondo.add(fieldNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        labelNombreProducto5.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreProducto5.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        labelNombreProducto5.setText("Email");
        panelFondo.add(labelNombreProducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 132, 70, 40));

        fieldEmail.setText("alvaro.morcillo@hotmail.com");
        fieldEmail.setPlaceholder("");
        fieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailActionPerformed(evt);
            }
        });
        panelFondo.add(fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        labelNombreProducto6.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreProducto6.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        labelNombreProducto6.setText("Nombre");
        panelFondo.add(labelNombreProducto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 90, 40));

        fieldTelefono.setText("658700542");
        fieldTelefono.setPlaceholder("");
        panelFondo.add(fieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        labelNombreProducto7.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreProducto7.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        labelNombreProducto7.setText("Teléfono");
        panelFondo.add(labelNombreProducto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 100, 40));

        fieldDNI.setText("dniej21");
        fieldDNI.setPlaceholder("");
        fieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDNIActionPerformed(evt);
            }
        });
        panelFondo.add(fieldDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        labelNombreProducto4.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreProducto4.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        labelNombreProducto4.setText("DNI");
        panelFondo.add(labelNombreProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 182, 50, 40));

        labelNombreProducto9.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreProducto9.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        labelNombreProducto9.setText("Tipo de usuario");
        panelFondo.add(labelNombreProducto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        comboRol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        comboRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRolActionPerformed(evt);
            }
        });
        panelFondo.add(comboRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 250, -1));

        fieldNomUsuario1.setText("alvaromb");
        fieldNomUsuario1.setPlaceholder("");
        panelFondo.add(fieldNomUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 250, -1));

        labelNombreProducto8.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreProducto8.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        labelNombreProducto8.setText("Apellidos");
        panelFondo.add(labelNombreProducto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 100, 40));

        fieldApellidos.setText("Morcillo Barbero");
        fieldApellidos.setPlaceholder("");
        panelFondo.add(fieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        lblConsola.setBackground(new java.awt.Color(255, 255, 255));
        lblConsola.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblConsola.setForeground(new java.awt.Color(255, 0, 0));
        lblConsola.setText("Conexión establecida correctamente");
        panelFondo.add(lblConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 467, 490, 50));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        doClose(RET_CANCEL);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        // TODO add your handling code here:

        usuario.setNombreUsuario(fieldNomUsuario1.getText());
        usuario.setEmail(fieldEmail.getText());
        usuario.setDni(fieldDNI.getText());
        usuario.setTelefono(fieldTelefono.getText());
        usuario.setNombre(fieldNom.getText());
        usuario.setApellidos(fieldApellidos.getText());
        usuario.setContra(lblContraActual.getText());

        //Comprueba si  hay campos vacios
        if (!Util.comprobarCamposVacíos(componentes)) {

            //Comprueba si el email es correcto
            if (Util.validarEmail(usuario.getEmail())) {
                //Comprueba si el usuario ya existe
                if (OperacionesBDD.comprobarUsuarioExiste(usuario.getNombreUsuario())) {

                    try {
                        Dialog_Confirmar dialog = new Dialog_Confirmar((Frame) SwingUtilities.getWindowAncestor(this), true, 0000);

                        dialog.setVisible(true);

                        if (dialog.getReturnStatus() == 1) {
                            //Cambiar contraseña en la db
                            OperacionesBDD.añadirUsuario(usuario.getNombreUsuario(), usuario.getEmail(), usuario.getContra(),
                                    usuario.getNombre(), usuario.getApellidos(), usuario.getTelefono(), usuario.getDni());
                            System.out.println("Usuario añadido correctamente");
                            doClose(RET_OK);
                        }

                    } catch (SQLException ex) {
                        System.out.println("Error al añadir usuario");
                        Logger.getLogger(Dialog_nuevoUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    //todo bien

                } else {

                    lblConsola.setVisible(true);
                    lblConsola.setText("El usuario ya existe");

                    System.out.println("El usuario ya existe");
                }
            } else {
                lblConsola.setVisible(true);
                lblConsola.setText("El email instroducido no es correcto");
            }
        } else {
            lblConsola.setVisible(true);
            lblConsola.setText("Comprueba que no falta nada");
        }


    }//GEN-LAST:event_botonConfirmarActionPerformed

    private void lblContraActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblContraActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblContraActualActionPerformed

    private void comboRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRolActionPerformed

    private void fieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailActionPerformed

    private void fieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDNIActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover botonCancelar;
    private rojerusan.RSButtonHover botonConfirmar;
    private rojerusan.RSComboMetro comboRol;
    private rojerusan.RSMetroTextFullPlaceHolder fieldApellidos;
    private rojerusan.RSMetroTextFullPlaceHolder fieldDNI;
    private rojerusan.RSMetroTextFullPlaceHolder fieldEmail;
    private rojerusan.RSMetroTextFullPlaceHolder fieldNom;
    private rojerusan.RSMetroTextFullPlaceHolder fieldNomUsuario1;
    private rojerusan.RSMetroTextFullPlaceHolder fieldTelefono;
    private javax.swing.JLabel labelNombreProducto10;
    private javax.swing.JLabel labelNombreProducto11;
    private javax.swing.JLabel labelNombreProducto4;
    private javax.swing.JLabel labelNombreProducto5;
    private javax.swing.JLabel labelNombreProducto6;
    private javax.swing.JLabel labelNombreProducto7;
    private javax.swing.JLabel labelNombreProducto8;
    private javax.swing.JLabel labelNombreProducto9;
    private javax.swing.JLabel lblConsola;
    private rojeru_san.RSMPassView lblContraActual;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;

}
