/*
 * Copyright (C) 2019 Álvaro Morcillo Barbero
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ui.dialogs;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import util.OperacionesBDD;

/**
 *
 * @author alvaro2226
 */
public class Dialog_cambiarContraseña extends javax.swing.JDialog {

    public static final int ELIMINAR_PRODUCTO = 0;
    public static final int ELIMINAR_USUARIO = 1;
    public static final int ELIMINAR_PEDIDO = 2;
    public static final int CONFIRMAR_AÑADIR_USUARIO = 4;
    public static final int CONFIRMAR_CONTRASEÑA = 5;

    String nombreUsuario = null;
    private int accion = 100;
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    public Dialog_cambiarContraseña(java.awt.Frame parent, boolean modal, String nombreUsuario) {
        super(parent, modal);

        this.nombreUsuario = nombreUsuario;

        initComponents();

        pack();
        this.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width) / 2 - getWidth() / 2, (Toolkit.getDefaultToolkit().getScreenSize().height) / 2 - getHeight() / 2);

        this.lblConsola.setVisible(false);
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        botonConfirmar = new rojerusan.RSButtonHover();
        botonCancelar = new rojerusan.RSButtonHover();
        labelNombreProducto11 = new javax.swing.JLabel();
        lblContraActual = new rojeru_san.RSMPassView();
        labelNombreProducto12 = new javax.swing.JLabel();
        lblContraNueva = new rojeru_san.RSMPassView();
        labelNombreProducto13 = new javax.swing.JLabel();
        lblContraNuevaRepetida = new rojeru_san.RSMPassView();
        lblConsola = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonConfirmar.setBackground(new java.awt.Color(55, 147, 114));
        botonConfirmar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonConfirmar.setText("Confirmar ");
        botonConfirmar.setColorHover(new java.awt.Color(70, 198, 136));
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });
        panelFondo.add(botonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 90, -1));

        botonCancelar.setBackground(new java.awt.Color(235, 86, 64));
        botonCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCancelar.setText("Cancelar");
        botonCancelar.setColorHover(new java.awt.Color(255, 153, 153));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelFondo.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 90, -1));

        labelNombreProducto11.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreProducto11.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        labelNombreProducto11.setText("Contraseña actual");
        panelFondo.add(labelNombreProducto11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 200, 40));

        lblContraActual.setPlaceholder("");
        lblContraActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblContraActualActionPerformed(evt);
            }
        });
        panelFondo.add(lblContraActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        labelNombreProducto12.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreProducto12.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        labelNombreProducto12.setText("Nueva contraseña");
        panelFondo.add(labelNombreProducto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 40));

        lblContraNueva.setPlaceholder("");
        lblContraNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblContraNuevaActionPerformed(evt);
            }
        });
        panelFondo.add(lblContraNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        labelNombreProducto13.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreProducto13.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        labelNombreProducto13.setText("Repite la contraseña");
        panelFondo.add(labelNombreProducto13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 220, 40));

        lblContraNuevaRepetida.setPlaceholder("");
        lblContraNuevaRepetida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblContraNuevaRepetidaActionPerformed(evt);
            }
        });
        panelFondo.add(lblContraNuevaRepetida, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        lblConsola.setBackground(new java.awt.Color(255, 255, 255));
        lblConsola.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblConsola.setForeground(new java.awt.Color(255, 0, 0));
        lblConsola.setText("Contraseña incorrecta");
        panelFondo.add(lblConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 280, 40));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        doClose(RET_CANCEL);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        try {
            // TODO add your handling code here:

            OperacionesBDD.iniciarConexion();
            boolean contraCorrecta = OperacionesBDD.comprobarContraseña(nombreUsuario, lblContraActual.getText());

            if (contraCorrecta) {
                System.out.println("La contraseña es correcta");
            } else {
                System.out.println("La contraseña es incorrecta");
                this.lblConsola.setVisible(true);
                this.lblConsola.setText("Contraseña incorrecta");
            }

            if (this.lblContraNueva.getText().equals(this.lblContraNuevaRepetida.getText()) && contraCorrecta) {
                try {

                    System.out.println(lblContraActual.getText() + " -> " + lblContraNueva.getText() + "   " + lblContraNuevaRepetida.getText());
                    Dialog_Confirmar dialog = new Dialog_Confirmar((Frame) SwingUtilities.getWindowAncestor(this), true, 0000);

                    dialog.setVisible(true);

                    if (dialog.getReturnStatus() == 1) {
                        //Cambiar contraseña en la db
                        OperacionesBDD.cambiarContraseña(nombreUsuario, lblContraNueva.getText());
                        doClose(RET_OK);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Dialog_cambiarContraseña.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                this.lblConsola.setVisible(true);

                if (contraCorrecta) {
                    this.lblConsola.setText("Las contraseñas no coinciden");
                }
            }
            OperacionesBDD.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(Dialog_cambiarContraseña.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dialog_cambiarContraseña.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonConfirmarActionPerformed

    private void lblContraActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblContraActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblContraActualActionPerformed

    private void lblContraNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblContraNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblContraNuevaActionPerformed

    private void lblContraNuevaRepetidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblContraNuevaRepetidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblContraNuevaRepetidaActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover botonCancelar;
    private rojerusan.RSButtonHover botonConfirmar;
    private javax.swing.JLabel labelNombreProducto11;
    private javax.swing.JLabel labelNombreProducto12;
    private javax.swing.JLabel labelNombreProducto13;
    private javax.swing.JLabel lblConsola;
    private rojeru_san.RSMPassView lblContraActual;
    private rojeru_san.RSMPassView lblContraNueva;
    private rojeru_san.RSMPassView lblContraNuevaRepetida;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;

}
