/*
 * Copyright (C) 2019 Álvaro Morcillo Barbero
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ui.dialogs;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author alvaro2226
 */
public class Dialog_Confirmar extends javax.swing.JDialog {

    public static final int ELIMINAR_PRODUCTO = 0;
    public static final int ELIMINAR_USUARIO = 1;
    public static final int ELIMINAR_PEDIDO = 2;
    public static final int CONFIRMAR_AÑADIR_USUARIO = 4;
    public static final int CONFIRMAR_CONTRASEÑA = 5;

    private int accion = 100;
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    public Dialog_Confirmar(java.awt.Frame parent, boolean modal,int accion) {
        super(parent, modal);

        this.accion = accion;
        initComponents();
        
        pack();
        this.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width)/2 - getWidth()/2, (Toolkit.getDefaultToolkit().getScreenSize().height)/2 - getHeight()/2);

    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        lblSeguro2 = new javax.swing.JLabel();
        lblSeguro1 = new javax.swing.JLabel();
        botonConfirmar = new rojerusan.RSButtonHover();
        botonCancelar = new rojerusan.RSButtonHover();

        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSeguro2.setBackground(new java.awt.Color(255, 255, 255));
        lblSeguro2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblSeguro2.setText("No hay vuelta atrás..");
        panelFondo.add(lblSeguro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 30));

        lblSeguro1.setBackground(new java.awt.Color(255, 255, 255));
        lblSeguro1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblSeguro1.setText("¿Estas seguro?");
        panelFondo.add(lblSeguro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 40));

        botonConfirmar.setBackground(new java.awt.Color(55, 147, 114));
        botonConfirmar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonConfirmar.setText("Confirmar ");
        botonConfirmar.setColorHover(new java.awt.Color(70, 198, 136));
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });
        panelFondo.add(botonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, -1));

        botonCancelar.setBackground(new java.awt.Color(235, 86, 64));
        botonCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCancelar.setText("Cancelar");
        botonCancelar.setColorHover(new java.awt.Color(255, 153, 153));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        panelFondo.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 90, -1));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        // TODO add your handling code here:
        
        switch(accion){
            case ELIMINAR_PRODUCTO: {
                
            }
                
        }
        
        doClose(RET_OK);
    }//GEN-LAST:event_botonConfirmarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        doClose(RET_CANCEL);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover botonCancelar;
    private rojerusan.RSButtonHover botonConfirmar;
    private javax.swing.JLabel lblSeguro1;
    private javax.swing.JLabel lblSeguro2;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;

}
